//---------------------------------------------------------------------------

#ifndef PrnFactoryH
#define PrnFactoryH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <Qrctrls.hpp>
#include <QuickRpt.hpp>
#include <QRCtrls.hpp>
//---------------------------------------------------------------------------
class TPrnFactoryForm : public TForm
{
__published:	// IDE-managed Components
	TQuickRep *PrnView;
	TQRBand *PageHeaderBand1;
	TQRLabel *QRLabel1;
	TQRGroup *QRGroup1;
	TQRLabel *QRLabel2;
	TQRDBText *mf_code;
	TQRLabel *QRLabel3;
	TQRDBText *QRDBText2;
	TQRLabel *QRLabel4;
	TQRDBText *QRDBText3;
	TQRShape *QRShape1;
	TQRLabel *QRLabel5;
	TQRDBText *QRDBText4;
	TQRShape *QRShape2;
	TQRLabel *QRLabel6;
	TQRShape *QRShape3;
	TQRLabel *QRLabel7;
	TQRShape *QRShape4;
	TQRLabel *QRLabel8;
	TQRShape *QRShape5;
	TQRLabel *QRLabel9;
	TQRShape *QRShape6;
	TQRShape *QRShape7;
	TQRShape *QRShape8;
	TQRShape *QRShape9;
	TQRDBText *QRDBText5;
	TQRDBText *QRDBText6;
	TQRDBText *QRDBText7;
	TQRDBText *QRDBText8;
	TQRShape *QRShape10;
	TQRLabel *QRLabel10;
	TQRShape *QRShape11;
	TQRShape *QRShape12;
	TQRLabel *QRLabel11;
	TQRShape *QRShape13;
	TQRShape *QRShape14;
	TQRLabel *QRLabel12;
	TQRShape *QRShape15;
	TQRShape *QRShape16;
	TQRShape *QRShape17;
	TQRShape *QRShape18;
	TQRShape *QRShape19;
	TQRShape *QRShape20;
	TQRShape *QRShape21;
	TQRShape *QRShape22;
	TQRLabel *QRLabel13;
	TQRLabel *QRLabel14;
	TQRLabel *QRLabel15;
	TQRLabel *QRLabel16;
	TQRShape *QRShape23;
	TQRLabel *QRLabel17;
	TQRShape *QRShape24;
	TQRLabel *QRLabel18;
	TQRShape *QRShape25;
	TQRLabel *QRLabel19;
	TQRShape *QRShape26;
	TQRShape *QRShape27;
	TQRShape *QRShape28;
	TQRLabel *QRLabel20;
	TQRShape *QRShape29;
	TQRShape *QRShape30;
	TQRShape *QRShape31;
	TQRLabel *QRLabel21;
	TQRShape *QRShape32;
	TQRLabel *QRLabel22;
	TQRShape *QRShape33;
	TQRShape *QRShape34;
	TQRLabel *QRLabel23;
	TQRShape *QRShape35;
	TQRLabel *QRLabel24;
	TQRShape *QRShape36;
	TQRShape *QRShape37;
	TQRShape *QRShape38;
	TQRLabel *QRLabel25;
	TQRShape *QRShape39;
	TQRLabel *QRLabel26;
	TQRShape *QRShape40;
	TQRShape *QRShape41;
	TQRLabel *QRLabel27;
	TQRShape *QRShape42;
	TQRLabel *QRLabel28;
	TQRShape *QRShape43;
	TQRShape *QRShape44;
	TQRShape *QRShape45;
	TQRLabel *QRLabel29;
	TQRShape *QRShape46;
	TQRShape *QRShape47;
	TQRShape *QRShape48;
	TQRShape *QRShape49;
	TQRShape *QRShape50;
	TQRShape *QRShape51;
	TQRShape *QRShape52;
	TQRShape *QRShape53;
	TQRShape *QRShape54;
	TQRShape *QRShape55;
	TQRShape *QRShape56;
	TQRShape *QRShape57;
	TQRShape *QRShape58;
	TQRShape *QRShape59;
	TQRShape *QRShape60;
	TQRShape *QRShape61;
	TQRShape *QRShape62;
	TQRShape *QRShape63;
	TQRShape *QRShape64;
	TQRShape *QRShape65;
	TQRLabel *QRLabel30;
	TQRLabel *QRLabel31;
	TQRLabel *QRLabel32;
	TQRLabel *QRLabel33;
	TQRLabel *QRLabel34;
	TQRLabel *QRLabel35;
	TQRLabel *QRLabel36;
	TQRLabel *QRLabel37;
	TQRLabel *QRLabel38;
	TQRLabel *QRLabel39;
	TQRLabel *QRLabel40;
	TQRLabel *QRLabel41;
	TQRLabel *QRLabel42;
	TQRDBText *QRDBText9;
	TQRDBText *QRDBText10;
	TQRDBText *QRDBText11;
	TQRDBText *QRDBText12;
	TQRDBText *QRDBText13;
	TQRDBText *QRDBText14;
	TQRDBText *QRDBText15;
	TQRDBText *QRDBText16;
	TQRDBText *QRDBText17;
	TQRLabel *QRLabel43;
	TQRDBText *QRDBText18;
	TQRDBText *QRDBText19;
	TQRDBText *QRDBText20;
	TQRDBText *QRDBText21;
	TQRDBText *QRDBText22;
	TQRDBText *QRDBText23;
	TQRLabel *txtProxy1;
	TQRLabel *txtProxy2;
	TQRLabel *txtProxy3;
	TQRLabel *txtProxy4;
	TQRLabel *txtProxy5;
	TQRLabel *txtProxy6;
	TQRLabel *txtProxy7;
	TQRLabel *txtProxy8;
	TQRDBText *QRDBText1;
	TQRDBText *QRDBText24;
	TQRLabel *QRLabel44;
	TQRLabel *QRLabel45;
	void __fastcall PageHeaderBand1BeforePrint(TQRCustomBand *Sender,
          bool &PrintBand);
private:	// User declarations
public:		// User declarations
	__fastcall TPrnFactoryForm(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TPrnFactoryForm *PrnFactoryForm;
//---------------------------------------------------------------------------
#endif
