#ifndef  __SUNTEK_TELECOM_LAODY_GRACESTOCK_GLOBALCONST__
#define  __SUNTEK_TELECOM_LAODY_GRACESTOCK_GLOBALCONST__

OPERATOR_DATA g_theOperator;

#endif  //__SUNTEK_TELECOM_LAODY_GRACESTOCK_GLOBALCONST__





